#Application Settings
#Wed Mar 18 16:38:32 GMT-05:00 2026
app.language=en_US
app.name=Notepad
app.theme=com.formdev.flatlaf.themes.FlatMacDarkLaf
editor.font.family=JetBrains Mono
editor.font.size=14
editor.wrap=true
window.height=556
window.maximized=false
window.width=758
window.x=558
window.y=243
